# Generated by Django 4.1.1 on 2022-09-20 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lables', '0001_initial'),
        ('notes', '0002_alter_notes_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='labels',
            field=models.ManyToManyField(to='lables.labels'),
        ),
    ]
