# Generated by Django 4.1.1 on 2022-09-21 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_notes_collaborator'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
