# Generated by Django 4.1.1 on 2022-09-21 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_notes_is_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='is_archive',
            field=models.BooleanField(default=False),
        ),
    ]
