# Generated by Django 4.1.1 on 2022-09-22 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_notes_is_archive'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='collaborator',
            new_name='user_collaborator',
        ),
    ]
