# Generated by Django 4.1.1 on 2022-09-22 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_rename_collaborator_notes_user_collaborator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='user_collaborator',
            new_name='collaborator',
        ),
    ]
