# Generated by Django 4.1.1 on 2022-09-28 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiddleWareModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('count', models.IntegerField(default=1)),
            ],
        ),
    ]
