# Generated by Django 4.1.1 on 2022-09-22 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='collabrator',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
