# Generated by Django 4.1.1 on 2022-09-28 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_middlewaremodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='middlewaremodel',
            name='count',
            field=models.IntegerField(),
        ),
    ]
