# Generated by Django 4.1.1 on 2022-09-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_collabrator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='collabrator',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
