# Generated by Django 4.1.1 on 2022-09-29 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_middlewaremodel_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='middlewaremodel',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
