# Generated by Django 4.1.1 on 2022-09-22 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_collabrator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='collabrator',
        ),
    ]
